updated kustomize-objects-namespaces.yaml

diff --git a/.github/workflows/kustomize-objects-namespaces.yaml b/.github/workflows/kustomize-objects-namespaces.yaml
--- a/.github/workflows/kustomize-objects-namespaces.yaml
+++ b/.github/workflows/kustomize-objects-namespaces.yaml
@@ -108,7 +108,11 @@ jobs:
             fi
             echo "$kustomization"
             cp -fv -- "$kustomization" kustomization.yaml
-            kustomize build --enable-helm | kubectl apply -f -
+            if ! kustomize build --enable-helm | kubectl apply -f - --server-side; then
+              echo "Kustomize | Kubectl Apply failed. Waiting 5 secs before trying again"
+              sleep 5
+              kustomize build --enable-helm | kubectl apply -f -
+            fi
             echo
           done
 
